title: Boopy The Noob
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
math: katex

url: https://just-the-docs.github.io

callouts:
  highlight:
    color: yellow